apiVersion: v2
name: seatrain
description: A Helm chart for Kubernetes deployment of Rails apps
type: application
version: 0.1.0
appVersion: 1.0

dependencies:
- name: redis
  version: 10.2.1
  repository: "@stable"
