image:
  repository: quay.io/lewagon/APP_NAME
  tag: latest
  pullPolicy: Always

# NOTE (@progapandist) A pull secret of that name needs to be created
# manually in the cluster. Refer to @progapandist for instructions,
# but normally it's already done by the time you see this.
imagePullSecrets:
  - name: lewagon-pull-secret
nameOverride: ""
fullnameOverride: ""

rails:
  replicaCount: 1

sidekiq:
  replicaCount: 1

# ENV variables declared here will be set for both Rails and Sidekiq pods
commonEnv:
  # IMPORTANT!
  # Unsets the build value that skips master_key validation so initalizers can fire at runtime
  ASSETS_PRECOMPILE: ""


# Values used to generate secrets at chart install/upgrade.
# These values need to be injected through shell env/CI secrets,
# Don't set them here and don't commit to source control.
dbConnectionString:
railsMasterKey:

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.io/cluster-issuer: production-tls-issuer
    # IMPORTANT, we want to force HTTPS 301 and HSTS on Rails level
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # To avoid double HSTS headers,
    # edit nginx-configuration ConfigMap in nginx-ingress namespace
    # to include
    # ----
    # data:
    #   hsts: "false"
  hosts:
    - host: SSL_HOST
      paths: ["/"]

  tls:
    - secretName: tls-cert
      hosts:
        - SSL_HOST

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

redis:
  cluster:
    enabled: true
    slaveCount: 2
  usePassword: false
  # By default, FLUSH and FLUSHALL are disabled in bitnami/redis chart
  master:
    disableCommands: []
