apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "APP_NAME.fullname" . }}-rails
  labels:
    {{- include "APP_NAME.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.rails.replicaCount }}
  selector:
    matchLabels:
      {{- include "APP_NAME.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "APP_NAME.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "APP_NAME.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          command:
            - rails
          args:
            - "server"
            - "-b"
            - "0.0.0.0"
          envFrom:
          - configMapRef:
              name: common-env
          {{if .Values.dbConnectionString }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-connection-string
                  key: db_connection_string
            {{ end }}
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: rails-master-key
                  key: rails_master_key
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            timeoutSeconds: 5
            failureThreshold: 3
            periodSeconds: 5
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            timeoutSeconds: 5
            failureThreshold: 3
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
