{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "seatrain.serviceAccountName" . }}
  labels:
{{ include "seatrain.labels" . | nindent 4 }}
{{- end -}}
